In [1]:
import pandas as pd
import numpy as np

In [5]:
fortuneDf= pd.read_csv("fortune1000.csv")

In [8]:
fortuneDf

,Rank,Company,Sector,Industry,Location,Revenue,Profits,Employees
0,1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
1,2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
2,3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
3,4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
4,5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
...,...,...,...,...,...,...,...,...
995,996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
996,997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
997,997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
998,999,Wendy’s,"Hotels, Resturants & Leisure",Food Services,"Dublin, OH",1896,161,21200
999,1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480

In [21]:
sectorDf= fortuneDf.groupby(['Sector'])

In [24]:
sectorDf['Industry']

In [26]:
sectorDf.count()

,Rank,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,,
Aerospace & Defense,20,20,20,20,20,20,20
Apparel,15,15,15,15,15,15,15
Business Services,51,51,51,51,51,51,51
Chemicals,30,30,30,30,30,30,30
Energy,122,122,122,122,122,122,122
Engineering & Construction,26,26,26,26,26,26,26
Financials,139,139,139,139,139,139,139
Food and Drug Stores,15,15,15,15,15,15,15
"Food, Beverages & Tobacco",43,43,43,43,43,43,43
Health Care,75,75,75,75,75,75,75
"Hotels, Resturants & Leisure",25,25,25,25,25,25,25
Household Products,28,28,28,28,28,28,28
Industrials,46,46,46,46,46,46,46
Materials,43,43,43,43,43,43,43
Media,25,25,25,25,25,25,25
Motor Vehicles & Parts,24,24,24,24,24,24,24
Retailing,80,80,80,80,80,80,80
Technology,102,102,102,102,102,102,102
Telecommunications,15,15,15,15,15,15,15
Transportation,36,36,36,36,36,36,36
Wholesalers,40,40,40,40,40,40,40

In [27]:
sectorDf.max()

,Rank,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,,
Aerospace & Defense,987,Woodward,Aerospace and Defense,"Wichita, KS",96114,7608,197200
Apparel,917,Wolverine World Wide,Apparel,"Winston-Salem, NC",30601,3273,65300
Business Services,993,Western Union,Waste Management,"Troy, MI",19330,6328,216500
Chemicals,949,Westlake Chemical,Chemicals,"Wilmington, DE",48778,7685,52000
Energy,997,Xcel Energy,Utilities: Gas and Electric,"Washington, DC",246204,16150,75600
Engineering & Construction,994,Tutor Perini,Homebuilders,"Watsonville, CA",18114,803,92000
Financials,996,Zions Bancorp.,Securities,"Worcester, MA",210821,24442,331000
Food and Drug Stores,928,Whole Foods Market,Food and Drug Stores,"Woonsocket, RI",153290,5237,431000
"Food, Beverages & Tobacco",954,WhiteWave Foods,Tobacco,"Winston-Salem, NC",67702,7351,263000
Health Care,978,inVentiv Health,Wholesalers: Health Care,"York, PA",181241,18108,203500
"Hotels, Resturants & Leisure",999,Yum Brands,"Hotels, Casinos, Resorts","Wyomissing, PA",25413,5920,505000
Household Products,992,Vista Outdoor,Miscellaneous,"Zeeland, MI",78756,7036,110000
Industrials,1000,Zebra Technologies,Miscellaneous,"Wilmerding, PA",140389,4833,333000
Materials,986,Worthington Industries,"Packaging, Containers","Wyomissing, PA",22534,991,60000
Media,989,iHeartMedia,"Publishing, Printing","Sussex, WI",52465,8382,185000
Motor Vehicles & Parts,979,Wabash National,Motor Vehicles and Parts,"Van Buren Township, MI",152356,9687,215000
Retailing,973,hhgregg,Specialty Retailers: Other,"York, PA",482130,14694,2300000
Technology,990,salesforce.com,Semiconductors and Other Electronic Components,"Woburn, MA",233715,53394,411798
Telecommunications,786,Windstream Holdings,Telecommunications,"Stamford, CT",146801,17879,281450
Transportation,974,YRC Worldwide,"Trucking, Truck Leasing","Thomasville, NC",58363,7610,341240
Wholesalers,991,World Fuel Services,Wholesalers: Food and Grocery,"Waltham, MA",48681,1472,78500

In [28]:
sectorDf['Company'].sum()

Sector
Aerospace & Defense             BoeingUnited TechnologiesLockheed MartinGenera...
Apparel                         NikeVFPVHRalph LaurenHanesbrandsLevi StraussCo...
Business Services               ManpowerGroupOmnicom GroupAramarkVisaWaste Man...
Chemicals                       Dow ChemicalDuPontPPG IndustriesMonsantoEcolab...
Energy                          Exxon MobilChevronPhillips 66Valero EnergyMara...
Engineering & Construction      FluorAECOMJacobs Engineering GroupD.R. HortonL...
Financials                      Berkshire HathawayFannie MaeJ.P. Morgan ChaseB...
Food and Drug Stores            CVS HealthKrogerWalgreens Boots AlliancePublix...
Food, Beverages & Tobacco       Archer Daniels MidlandPepsiCoCoca-ColaTyson Fo...
Health Care                     McKessonUnitedHealth GroupAmerisourceBergenCar...
Hotels, Resturants & Leisure    McDonald’sStarbucksMarriott InternationalYum B...
Household Products              Procter & GambleKimberly-ClarkColgate-Palmoliv...
Industrials                     General ElectricCaterpillarHoneywell Internati...
Materials                       AlcoaInternational PaperNucorUnited States Ste...
Media                           DisneyTwenty-First Century FoxTime WarnerCBSVi...
Motor Vehicles & Parts          General MotorsFord MotorJohnson ControlsPaccar...
Retailing                       WalmartCostcoHome DepotTargetLowe’sBest BuyTJX...
Technology                      AppleAmazon.comHPMicrosoftIBMAlphabetIntelCisc...
Telecommunications              AT&TVerizonComcastTime Warner CableCenturyLink...
Transportation                  UPSFedExAmerican Airlines GroupDelta Air Lines...
Wholesalers                     SyscoIngram MicroWorld Fuel ServicesAvnetTech ...
Name: Company, dtype: object